export const projects = [
  {
    id: 1,
    name: "Tic Tac Toe",
    linkName: "tic-tac-toe",
    screenshot: "tic_tac_toe.png",
    info: "Tic Tac Toe's project was the most challenging task I have done before. User can play against another user and CPU also. It's fully responsive so you can view the optimal layout for the game depending on your device's screen size.",
    url: "https://4zj27p.csb.app/",
    preview: "tic_tac_toe_preview.jpg",
  },
  {
    id: 2,
    name: "GitHub User Search",
    linkName: "github-user-search",
    screenshot: "github.png",
    info: "User can search any person who is logged in a Github and switch theme from dark to light. It was first time where I used data from API like asynchronous functaion and await keywords",
    preview: "github_preview.jpg",
  },
  {
    id: 3,
    name: "Tip Calculator",
    linkName: "tip-calculator",
    screenshot: "calculator.png",
    info: "I made this project twice. First with Vanilla JS and next with ReactJS. User can Calculate the correct tip and total cost of the bill per person. It's fully responsive",
    preview: "calculator_preview.jpg",
  },
  {
    id: 4,
    name: "Interactive Pricing Component",
    linkName: "interactive-pricing-component",
    screenshot: "pricingcomponent.png",
    info: "I would like to share this project because It was first time where I used Tailwind CSS and I gained really good experience. Users can choose whichever package and price are accaptable for them",
    preview: "pricingcomponent_preview.png",
  },
  {
    id: 5,
    name: "Art Gallery",
    linkName: "art-gallery-website",
    screenshot: "artgallery.png",
    info: "This project required me to build  a fully responsive markup for Modern Art Gallery with 2 pages. I used HTML5, along with CSS Grid and Flexbox.",
    url: "https://4zj27p.csb.app/",
    preview: "artgallery_preview.jpg",
  },
];
